dashboard:
  type: dashboard # Assuming 'dashboard' is the correct type key
  # Define the list of possible states the dashboard can represent or trigger
  # This 'states' key was missing, causing the error
  states:
    - name: inactive     # A unique name for the state
      nice_name: Inactive # Optional: A user-friendly name for the UI
      plugin: []         # List of xbot plugins expected/required for this state
      process: []        # List of concert_launcher processes expected/required for this state
    - name: ready        # Another example state
      nice_name: Ready
      plugin: []
      process: []
    # Add other states relevant to your application here following the same format
    # - name: jogging_cartesian
    #   nice_name: Jogging (Cartesian)
    #   process: [<list_of_processes>]
    #   plugin: [<list_of_plugins>]
  # all_plugins: [<list_all_relevant_plugin_names>]
  # all_processes: [<list_all_relevant_process_names>]
    
# Section for the internal GUI Launcher component
launcher:
  type: launcher
  # **THIS KEY IS REQUIRED** to fix the current 'KeyError: launcher_config'
  # It must point to a concert_launcher-style YAML file defining processes for the GUI.
  launcher_config: nexus_launcher_config.yaml # Example: using the main one