context:
  session: nexus_real
  params:
    hw_type: ec_imp

# components
roscore:
  cmd: rostopic list &> /dev/null || roscore
  ready_check: rostopic list

xbot2:
  cmd: xbot2-core --hw ec_imp -C $(rospack find nexus_config)/nexus_basic.yaml
  ready_check: timeout 5 rostopic echo /xbotcore/joint_states -n 1
  depends:
    - roscore
    
all:
  cmd: tail -f /dev/null  # Runs forever without output
  persistent: true
  depends:
    - xbot2