context:
  session: nexus_real
  params:
    hw_type: ec_imp
  .defines:

    - &embedded embedded@10.24.12.100
    - &control nexus@10.24.12.102
    - &vision nexus@10.24.12.101
    - &docker-xeno  "hhcmhub/${BASE_IMAGE_NAME}-xeno-v$KERNEL_VER:$TAGNAME"
    - &docker-dev  hhcmhub/${BASE_IMAGE_NAME}-base:$TAGNAME"
    - &docker-loco hhcmhub/${BASE_IMAGE_NAME}-locomotion:$TAGNAME"

# components
roscore:
  cmd: rostopic list &> /dev/null || roscore
  ready_check: rostopic list

ecat:
  cmd: ecat_master
  machine: *embedded
  docker: *docker-xeno
  
xbot2:
  cmd: xbot2-core --hw {hw_type} -C $(rospack find nexus_config)/nexus_basic.yaml
  ready_check: timeout 5 rostopic echo /xbotcore/joint_states -n 1
  depends: []
  docker: *docker-xeno
  variants:
    verbose:
      cmd: "{cmd} -V"
    ctrl:
      - ec_idle:
          params:
            hw_type: ec_idle
      - ec_pos:
          params:
            hw_type: ec_pos
      - dummy:
          params:
            hw_type: dummy
    
real:
  cmd: tail -f /dev/null  # Runs forever without output
  persistent: true
  depends:
    - xbot2